apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: twp2t7uwl-nodejs 
  janus-idp.io/tekton: twp2t7uwl-nodejs
  backstage.io/kubernetes-id: twp2t7uwl-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: twp2t7uwl-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml