apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: twp2t7uwl-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: twp2t7uwl-nodejs 
  name: twp2t7uwl-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: twp2t7uwl-nodejs 
